namespace Baksteen.Waves;

using System.Runtime.InteropServices;
using Windows.Win32.Foundation;

internal static class ErrorLut
{
    private static Dictionary<int, string> _known = [];

    static ErrorLut()
    {
        _known[HRESULT.AUDCLNT_E_UNSUPPORTED_FORMAT.Value] = "AUDCLNT_E_UNSUPPORTED_FORMAT";
        _known[HRESULT.AUDCLNT_E_NOT_INITIALIZED.Value] = "AUDCLNT_E_NOT_INITIALIZED";
        _known[HRESULT.AUDCLNT_E_ALREADY_INITIALIZED.Value] = "AUDCLNT_E_ALREADY_INITIALIZED";
        _known[HRESULT.AUDCLNT_E_WRONG_ENDPOINT_TYPE.Value] = "AUDCLNT_E_WRONG_ENDPOINT_TYPE";
        _known[HRESULT.AUDCLNT_E_DEVICE_INVALIDATED.Value] = "AUDCLNT_E_DEVICE_INVALIDATED";
        _known[HRESULT.AUDCLNT_E_NOT_STOPPED.Value] = "AUDCLNT_E_NOT_STOPPED";
        _known[HRESULT.AUDCLNT_E_BUFFER_TOO_LARGE.Value] = "AUDCLNT_E_BUFFER_TOO_LARGE";
        _known[HRESULT.AUDCLNT_E_OUT_OF_ORDER.Value] = "AUDCLNT_E_OUT_OF_ORDER";
        _known[HRESULT.AUDCLNT_E_INVALID_SIZE.Value] = "AUDCLNT_E_INVALID_SIZE";
        _known[HRESULT.AUDCLNT_E_DEVICE_IN_USE.Value] = "AUDCLNT_E_DEVICE_IN_USE";
        _known[HRESULT.AUDCLNT_E_BUFFER_OPERATION_PENDING.Value] = "AUDCLNT_E_BUFFER_OPERATION_PENDING";
        _known[HRESULT.AUDCLNT_E_THREAD_NOT_REGISTERED.Value] = "AUDCLNT_E_THREAD_NOT_REGISTERED";
        _known[HRESULT.AUDCLNT_E_EXCLUSIVE_MODE_NOT_ALLOWED.Value] = "AUDCLNT_E_EXCLUSIVE_MODE_NOT_ALLOWED";
        _known[HRESULT.AUDCLNT_E_ENDPOINT_CREATE_FAILED.Value] = "AUDCLNT_E_ENDPOINT_CREATE_FAILED";
        _known[HRESULT.AUDCLNT_E_SERVICE_NOT_RUNNING.Value] = "AUDCLNT_E_SERVICE_NOT_RUNNING";
        _known[HRESULT.AUDCLNT_E_EVENTHANDLE_NOT_EXPECTED.Value] = "AUDCLNT_E_EVENTHANDLE_NOT_EXPECTED";
        _known[HRESULT.AUDCLNT_E_EXCLUSIVE_MODE_ONLY.Value] = "AUDCLNT_E_EXCLUSIVE_MODE_ONLY";
        _known[HRESULT.AUDCLNT_E_BUFDURATION_PERIOD_NOT_EQUAL.Value] = "AUDCLNT_E_BUFDURATION_PERIOD_NOT_EQUAL";
        _known[HRESULT.AUDCLNT_E_EVENTHANDLE_NOT_SET.Value] = "AUDCLNT_E_EVENTHANDLE_NOT_SET";
        _known[HRESULT.AUDCLNT_E_INCORRECT_BUFFER_SIZE.Value] = "AUDCLNT_E_INCORRECT_BUFFER_SIZE";
        _known[HRESULT.AUDCLNT_E_BUFFER_SIZE_ERROR.Value] = "AUDCLNT_E_BUFFER_SIZE_ERROR";
        _known[HRESULT.AUDCLNT_E_CPUUSAGE_EXCEEDED.Value] = "AUDCLNT_E_CPUUSAGE_EXCEEDED";
        _known[HRESULT.AUDCLNT_E_BUFFER_ERROR.Value] = "AUDCLNT_E_BUFFER_ERROR";
        _known[HRESULT.AUDCLNT_E_BUFFER_SIZE_NOT_ALIGNED.Value] = "AUDCLNT_E_BUFFER_SIZE_NOT_ALIGNED";
        _known[HRESULT.AUDCLNT_E_INVALID_DEVICE_PERIOD.Value] = "AUDCLNT_E_INVALID_DEVICE_PERIOD";
        _known[HRESULT.AUDCLNT_E_INVALID_STREAM_FLAG.Value] = "AUDCLNT_E_INVALID_STREAM_FLAG";
        _known[HRESULT.AUDCLNT_E_ENDPOINT_OFFLOAD_NOT_CAPABLE.Value] = "AUDCLNT_E_ENDPOINT_OFFLOAD_NOT_CAPABLE";
        _known[HRESULT.AUDCLNT_E_OUT_OF_OFFLOAD_RESOURCES.Value] = "AUDCLNT_E_OUT_OF_OFFLOAD_RESOURCES";
        _known[HRESULT.AUDCLNT_E_OFFLOAD_MODE_ONLY.Value] = "AUDCLNT_E_OFFLOAD_MODE_ONLY";
        _known[HRESULT.AUDCLNT_E_NONOFFLOAD_MODE_ONLY.Value] = "AUDCLNT_E_NONOFFLOAD_MODE_ONLY";
        _known[HRESULT.AUDCLNT_E_RESOURCES_INVALIDATED.Value] = "AUDCLNT_E_RESOURCES_INVALIDATED";
        _known[HRESULT.AUDCLNT_E_RAW_MODE_UNSUPPORTED.Value] = "AUDCLNT_E_RAW_MODE_UNSUPPORTED";
        _known[HRESULT.AUDCLNT_E_ENGINE_PERIODICITY_LOCKED.Value] = "AUDCLNT_E_ENGINE_PERIODICITY_LOCKED";
        _known[HRESULT.AUDCLNT_E_ENGINE_FORMAT_LOCKED.Value] = "AUDCLNT_E_ENGINE_FORMAT_LOCKED";
        _known[HRESULT.AUDCLNT_E_HEADTRACKING_ENABLED.Value] = "AUDCLNT_E_HEADTRACKING_ENABLED";
        _known[HRESULT.AUDCLNT_E_HEADTRACKING_UNSUPPORTED.Value] = "AUDCLNT_E_HEADTRACKING_UNSUPPORTED";
        _known[HRESULT.AUDCLNT_E_EFFECT_NOT_AVAILABLE.Value] = "AUDCLNT_E_EFFECT_NOT_AVAILABLE";
        _known[HRESULT.AUDCLNT_E_EFFECT_STATE_READ_ONLY.Value] = "AUDCLNT_E_EFFECT_STATE_READ_ONLY";
        _known[HRESULT.AUDCLNT_E_POST_VOLUME_LOOPBACK_UNSUPPORTED.Value] = "AUDCLNT_E_POST_VOLUME_LOOPBACK_UNSUPPORTED";
    }

    public static string TranslateHRESULT(HRESULT hr)
    {
        if (_known.TryGetValue(hr.Value, out var msg))
        {
            return $"{msg} ({hr})";
        }
        else
        {
            return Marshal.GetPInvokeErrorMessage(hr);
        }
    }
}
